gigoogigeul/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views
from challengeapp import urls
from quizapp import urls
from shopapp import urls
from userapp import urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.main, name='main'),
    path('challengeapp/', include('challengeapp.urls')),
    path('quizapp/', include('quizapp.urls')),
    path('shopapp/', include('shopapp.urls')),
    path('userapp/', include('userapp.urls')),
    path('base/', views.main, name='base'),
    # path('signin', views.signin, name='signin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizapp/urls.py
from django.urls import path, include
from quizapp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('detailquiz/', views.detailquiz, name='detailquiz'),
    path('detailquiznote/', views.detailquiznote, name='detailquiznote'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiznote/', views.quiznote, name='quiznote'),
]

userapp/urls.py
from django.urls import path, include
from userapp import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('editinfo/', views.editinfo, name='editinfo'),
    path('editimage/', views.editimage, name='editimage'),
    path('editpw/', views.editpw, name='editpw'),

    path('findpw/', views.findpw, name='findpw'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signin_page/', views.signin_page, name='signin_page'),
    path('', include('django.contrib.auth.urls')),


    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),


    path('account/', include('allauth.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.


class CustomUser(AbstractUser):
    def __str__(self):
        return self.username

    nickname = models.CharField(max_length=20)
    profile_image = models.ImageField(upload_to='images/', blank=True)

class Challenge(models.Model):
    # challenge_id = models.IntegerField()
    challenge_name = models.CharField(max_length = 45)
    #applicant_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applicant_id')
    #participants_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='participants_id')
    categories = models.ManyToManyField('category',blank=True)
    introduction = models.CharField(max_length = 100, null=True)
    challenge_start = models.DateTimeField(auto_now=True)
    #term = models.DateTimeField()
    challenge_img = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.challenge_name

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Activity(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='a_user', primary_key=True)
    challenge_id = models.ForeignKey('main.Challenge', on_delete=models.CASCADE, related_name='myapp.Activity.challenge_id+')
    activity_title = models.CharField(max_length = 45, default="제목을 입력해주세요")
    activity_img = models.ImageField(upload_to='images/', null=True, blank=True)
    activity_content = models.TextField(max_length = 400, null=True)
    activity_date = models.DateTimeField()
    # activity_id = models.IntegerField()

    def __str__(self):
        return self.activity_title

class Challenge_mypage(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='c_user', primary_key=True)
    challenge_ing = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='challenge_ing', null=True)
    challenge_past = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='cmychallenge_past',null=True)

class Stamp(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stp_user', primary_key=True)
    activity_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activity_id', null=True) 
    challenge_id = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='myapp.Stamp.challenge_id+')

    # def __str__(self):
    #     return Challenge.challenge_name

class N_badge(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='nb_user', primary_key=True)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, max_length = 20, related_name='challenge')
    n30_badge = models.BooleanField(default = True, null=True) 
    n50_badge = models.BooleanField(default = True, null=True) 
    n70_badge = models.BooleanField(default = True, null=True) 
    n100_badge = models.BooleanField(default = True, null=True) 
    badge_date = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True, related_name='badge_date')

class Challenge_Badge(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cb_user', primary_key=True)
    challenge_past = models.ForeignKey(Challenge_mypage, on_delete=models.CASCADE, null=True, related_name='cbchallenge_past')

class Shop(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shop_user', primary_key=True)
    addchallenge_id = models.IntegerField(null=True)
    theme_id = models.IntegerField(null=True)
    theme_name = models.CharField(max_length = 45, null=True)
    theme_price = models.IntegerField(null=True)

class Point(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='p_user', primary_key=True)
    user_point = models.IntegerField()
    point_log_name = models.ForeignKey(Shop, on_delete=models.CASCADE, max_length = 45, related_name='point_log_name', null=True)
    point_log_price = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='point_log_price' ,null=True)

class Quiz(models.Model):
    quiz_id = models.IntegerField()
    quiz_content = models.CharField(max_length = 200, null=True)
    quiz_img = models.ImageField(upload_to='images/', null=True, blank=True)
    quiz_true = models.CharField(max_length = 100)
    quiz_false = models.CharField(max_length = 100)
    quiz_explanation = models.CharField(max_length = 300, null=True)
    #quiz_question = models.CharField(max_length = 200)

class Quiz_mypage(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='q_user', primary_key=True)
    quiz_pass = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_pass', null=True)
    quiz_nonepass = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_nonepass', null=True)

userapp/models.py
from django.db import models

# Create your models here.

userapp/forms.py
from django import forms
from django.forms import fields
from main.models import CustomUser
# from django.contrib.auth.models import User

class SigninForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password']
        labels = {'username': '이름', 'password': '비밀번호'}

class UserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password', 'email', 'nickname', 'profile_image']
        labels = {'username': '이름', 'password': '비밀번호', 'email': '이메일', 'nickname': '닉네임', 'profile_image': '프로필 사진'}

userapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .forms import SigninForm, UserForm
from main.models import CustomUser
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.http import HttpResponse

from django.views.generic.detail import DetailView
from django.views import View

# 비밀번호 재설정 import
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
from django.contrib.auth.forms import (
    AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm,
)
from django.urls import reverse_lazy



# Create your views here.
@login_required
def editinfo(request):
    if request.method == 'GET':
        return render(request, 'userapp/editinfo.html')

    elif request.method == 'POST':
        user = request.user
        email = request.POST.get('email')
        username = request.POST.get('username')
        nickname = request.POST.get('nickname')

        user.email = email
        user.username = username
        user.nickname = nickname

        user.save()

        return redirect('mypage')


@login_required
def editimage(request):
    Custom_user = CustomUser.objects.all()
    user = request.user

    if request.method == 'GET':
        # 프로필 삭제
        if request.GET.get('d'):
            user.profile_image.delete()
            return redirect('mypage')
            
        return render(request, 'userapp/editimage.html', {'Custom_user':Custom_user})

    elif request.method == 'POST':
        # 아무 사진 선택하지 않고 제출 => 프사 유지
        if not request.FILES:
            user.profile_image
        # 다른 프로필 사진으로 변경
        else:
            profile_image = request.FILES['profile_image']
            user.profile_image = profile_image

        user.save()

        return redirect('mypage')


@login_required
def editpw(request):
    Custom_user = CustomUser.objects.all()

    if request.method == 'GET':
        return render(request, 'userapp/editpw.html', {'Custom_user':Custom_user})

    elif request.method == 'POST':
        user = request.user
        pw = request.POST.get('pw')

        user.set_password(pw)
        user.save()

        return redirect('main')



def findpw(request):
    return render(request, 'userapp/findpw.html')

def signin_page(request):
    signin_form = SigninForm()
    return render(request, 'userapp/signin_page.html', {'signin_form': signin_form})

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            new_user = CustomUser.objects.create_user(username=form.cleaned_data['username'],
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password'],
            nickname=form.cleaned_data['nickname'],
            profile_image=form.cleaned_data['profile_image'])
            login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('main')
        # else:
        #     return HttpResponse('실패')
    else:
        form = UserForm()
        return render(request, 'userapp/signup.html', {'form': form})

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username, password = password)

        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            return HttpResponse("로그인 실패")

# 비밀번호 재설정
class MyPasswordResetView(PasswordResetView):
    success_url=reverse_lazy('login')
    template_name = 'userapp/password_reset_form.html'
    email_template_name = 'userapp/password_reset.html'
    mail_title="비밀번호 재설정"

    def form_valid(self, form):
        return super().form_valid(form)

class MyPasswordResetConfirmView(PasswordResetConfirmView):
    success_url=reverse_lazy('login')
    template_name = 'userapp/password_reset_confirm.html'

    def form_valid(self, form):
        return super().form_valid(form)

userapp/templates/userapp/editimage.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'userapp/css/jw_editimage.css' %}" />
{% endblock css %}

{% block content %}

<div class="all_box">
    <div class="edit_box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="editimage_intro">
                <h1 class="editimage">NEW PROFILE IMAGE</h1>
            </div>
            <hr>

            <br> <br>
            {% if user.is_authenticated %}
            {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" width="250" height="250" alt="profile_image" id="MY_PROFILE_b">
            {% else %}
            <img id="MY_PROFILE_b" src="{% static 'userapp/img/profile.png' %}" alt="{{user.nickname}}">
            {% endif %}
            {% endif %}
            <br><br><br>

            <div class="editimage_form">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="filebox">
                        <label for="ex_file">파일 선택</label>
                        <input type="file" id="ex_file" name="profile_image" value="{{ user.profile_image }}"
                            accept="image/*">
                    </div>

                    <button type="submit" class="submit">저장</button>

                </form>
            </div>

            <hr>

            <div class="del_image">
                <form action="" method="GET">
                    <input type="submit" value="프로필사진 삭제" name="d" class="submit">
                </form>
            </div>
        </form>
    </div>

</div>

{% endblock %}

userapp/templates/userapp/editinfo.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'userapp/css/jw_editinfo.css' %}" />
{% endblock css %}

{% block content %}

<div class="all_box">
    <div class="edit_box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <br> <br>
            {% if user.is_authenticated %}
            {% if user.profile_image %}
            <img src="{{ user.profile_image.url }}" width="250" height="250" alt="profile_image" id="MY_PROFILE_b">
            {% else %}
            <img id="MY_PROFILE_b" src="{% static 'userapp/img/profile.png' %}" alt="{{user.nickname}}">
            {% endif %}
            {% endif %}
            <br><br><br>
            <p class="p"><a class="info-input" href="{% url 'editimage' %}">프로필 사진 편집</a></p>
            <p class="p"><a class="info-input" href="{% url 'editpw' %}">비밀번호 수정</a></p>

            <hr>

            <div class="edit_form">
                <table>
                    <tbody>
                        <tr>
                            <td>아이디</td>
                            <td><input type="text" class="form-control" id="username" name="username"
                                    value="{{ user.username }}"></td>
                        </tr>
                        <tr>
                            <td>닉네임</td>
                            <td><input type="text" class="form-control" id="nickname" name="nickname"
                                    value="{{ user.nickname }}"></td>
                        </tr>
                        <tr>
                            <td>이메일</td>
                            <td><input type="email" class="form-control" id="email" name="email"
                                    value="{{ user.email }}">
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <br>
            <input type="submit" value="저장" class="submit">
        </form>
    </div>

</div>

{% endblock %}

userapp/templates/userapp/editpw.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'userapp/css/jw_editpw.css' %}" />
{% endblock css %}

{% block content %}

<!-- 비밀번호 칸을 공란으로 하고 저장하게 되면 다시는 로그인할 수 없음... -->

<div class="all_box">
    <div class="edit_box">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="editpw_intro">
                <h1 class="editpw">NEW PASSWORD</h1>
            </div>
            <hr>

            <div class="edit_form">
                <table>
                    <tbody>
                        <tr>
                            <td>새 비밀번호</td>
                            <td> <input type="password" class="td-color edit-input" id="pw" name="pw"
                                    placeholder="변경할 비밀번호를 입력하세요."></td>
                        </tr>
                        <tr>
                            ** 비밀번호를 재설정할 시, 다시 로그인 해야 합니다.
                        </tr>
                    </tbody>
                </table>
            </div>
            <br>
            <input type="submit" value="저장" class="submit">
        </form>
    </div>

</div>

{% endblock %}

userapp/templates/userapp/findpw.html
{% extends 'main/base.html' %}
{% block content %}
<h1>여기는 findpw</h1>
{% endblock %}

userapp/templates/userapp/signin_page.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'userapp/css/signin.css' %}" />
{% endblock css %}

<!-- 소셜 로그인 관련 -->
{% load socialaccount %}
{% providers_media_js %}

{% block content %}

<div class="all_box">

    <div class="signin_intro">
        <h1 class="signin">LOGIN</h1>
        <hr>
    </div>

    <div class="login_form">
        <form method="POST" action='/userapp/signin'>
            {% csrf_token %}
            <input class="id_pw" type="text" placeholder="ID" name="username" maxlength="150" required=""
                id="id_username"><br><br>
            <input class="id_pw" type="password" placeholder="PassWord" name="password" maxlength="128" required=""
                id="id_password"><br><br><br>

            <button type="submit" value="submit" class="in-in">로그인</button>
        </form>
    </div>

    <hr>
    <br>

    <div class="box">
        <div class="sns_login">
            <p class="intro">기존에 사용하던 계정이 있다면?</p>
            <a href="{% provider_login_url 'google' %}"><img class="social-img2"
                    src="{% static 'userapp/img/구글.png' %}"></a>
            <br>
            <a href="{% provider_login_url 'naver' %}"><img class="social-img2"
                    src="{% static 'userapp/img/네이버.png' %}"></a>
        </div>

        <br> <br>

        <div class="go_signup">
            <p class="intro">아직 계정이 없다면? <a class="signup" href="{% url 'signup' %}"> 회원가입</a></p>

        </div>
    </div>



</div>

{% endblock %}

userapp/templates/userapp/signup.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'userapp/css/signup.css' %}" />
{% endblock css %}

{% block content %}

<div class="all_box">
    <div class="signup_intro">
        <h1 class="signup">SIGNUP</h1>
        <hr>
    </div>

    <div class="signup_form">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tbody>
                    <tr>
                        <td>아이디</td>
                        <td>
                            <input type="text" placeholder="USERNAME" name="username" maxlength="150" required=""
                                id="id_username" class="up-id">
                        </td>
                    </tr>
                    <tr>
                        <td>비밀번호</td>
                        <td>
                            <input type="text" name="password" maxlength="128" required="" id="id_password"
                                class="up-pw" placeholder="PASSWORD">
                        </td>
                    </tr>
                    <tr>
                        <td>이메일</td>
                        <td>
                            <input type="email" placeholder="EMAIL" name="email" maxlength="254" id="id_email"
                                class="up-em">
                        </td>
                    </tr>
                    <tr>
                        <td>닉네임</td>
                        <td>
                            <input type="text" placeholder="NICKNAME" name="nickname" maxlength="20" required=""
                                id="id_nickname" class="up-nick">
                        </td>
                    </tr>
                    <tr>
                        <td>프로필 사진</td>
                        <td>
                            <br>
                            <input type="file" placeholder="PROFILEIMAGE" name="profile_image" accept="image/*"
                                id="id_profile_image">
                        </td>
                    </tr>
                </tbody>
            </table>

            <br> <br>
            <button class="up-up" type="submit" value="submit">회원가입</button>
        </form>
    </div>

    <hr>

    <div class="go_signin">
        <p class="signin_intro">이미 계정이 있다면? <a class="signin" href="{% url 'signin_page' %}"> 로그인</a></p>

    </div>
</div>

{% endblock %}