challengeapp/urls.py
from django.urls import path, include
from challengeapp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('allchallengeandsearch/', views.allchallengeandsearch, name='allchallengeandsearch'),
    path('addchallenge/', views.addchallenge, name='addchallenge'),
    path('detailchallenge/', views.detailchallenge, name='detailchallenge'),
    path('challengecategory/',views.categoryform, name='challengecategory'),
    path('challengeedit/', views.challengeedit, name='challengeedit'),
    path('activity/', views.activity, name='activity'),
    path('activitydetail/<str:activity_title>/', views.activitydetail, name='activitydetail'),
    path('mypage/', views.mypage, name='mypage'),
    path('newpost/writepost/', views.writepost, name='writepost'),
    path('postedit/<str:activity_title>/', views.postedit, name='postedit'),
    path('postdelete/<str:activity_title>/', views.postdelete, name='postdelete'),
    path('badge/', views.badge, name='badge'),
    path('search/', views.search, name='search'),
    path('more', views.more, name='more'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gigoogigeul/urls.py
from django.contrib import admin
from django.urls import path, include

from main import views
from challengeapp import urls
from quizapp import urls
from shopapp import urls
from userapp import urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.main, name='main'),
    path('challengeapp/', include('challengeapp.urls')),
    path('quizapp/', include('quizapp.urls')),
    path('shopapp/', include('shopapp.urls')),
    path('userapp/', include('userapp.urls')),
    path('base/', views.main, name='base'),
    # path('signin', views.signin, name='signin'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizapp/urls.py
from django.urls import path, include
from quizapp import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('detailquiz/', views.detailquiz, name='detailquiz'),
    path('detailquiznote/', views.detailquiznote, name='detailquiznote'),
    path('quiz/', views.quiz, name='quiz'),
    path('quiznote/', views.quiznote, name='quiznote'),
]

challengeapp/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.


class CustomUser(AbstractUser):
    def __str__(self):
        return self.username

    nickname = models.CharField(max_length=20)
    profile_image = models.ImageField(upload_to='images/', blank=True)

class Challenge(models.Model):
    # challenge_id = models.IntegerField()
    challenge_name = models.CharField(max_length = 45)
    #applicant_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='applicant_id')
    #participants_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='participants_id')
    categories = models.ManyToManyField('category',blank=True)
    introduction = models.CharField(max_length = 100, null=True)
    challenge_start = models.DateTimeField(auto_now=True)
    #term = models.DateTimeField()
    challenge_img = models.ImageField(upload_to='images/', blank=True)

    def __str__(self):
        return self.challenge_name

class Category(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Activity(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='a_user', primary_key=True)
    challenge_id = models.ForeignKey('main.Challenge', on_delete=models.CASCADE, related_name='myapp.Activity.challenge_id+')
    activity_title = models.CharField(max_length = 45, default="제목을 입력해주세요")
    activity_img = models.ImageField(upload_to='images/', null=True, blank=True)
    activity_content = models.TextField(max_length = 400, null=True)
    activity_date = models.DateTimeField()
    # activity_id = models.IntegerField()

    def __str__(self):
        return self.activity_title

class Challenge_mypage(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='c_user', primary_key=True)
    challenge_ing = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='challenge_ing', null=True)
    challenge_past = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='cmychallenge_past',null=True)

class Stamp(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='stp_user', primary_key=True)
    activity_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='activity_id', null=True) 
    challenge_id = models.ForeignKey(Challenge, on_delete=models.CASCADE, related_name='myapp.Stamp.challenge_id+')

    # def __str__(self):
    #     return Challenge.challenge_name

class N_badge(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='nb_user', primary_key=True)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, max_length = 20, related_name='challenge')
    n30_badge = models.BooleanField(default = True, null=True) 
    n50_badge = models.BooleanField(default = True, null=True) 
    n70_badge = models.BooleanField(default = True, null=True) 
    n100_badge = models.BooleanField(default = True, null=True) 
    badge_date = models.ForeignKey(Activity, on_delete=models.CASCADE, null=True, related_name='badge_date')

class Challenge_Badge(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cb_user', primary_key=True)
    challenge_past = models.ForeignKey(Challenge_mypage, on_delete=models.CASCADE, null=True, related_name='cbchallenge_past')

class Shop(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='shop_user', primary_key=True)
    addchallenge_id = models.IntegerField(null=True)
    theme_id = models.IntegerField(null=True)
    theme_name = models.CharField(max_length = 45, null=True)
    theme_price = models.IntegerField(null=True)

class Point(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='p_user', primary_key=True)
    user_point = models.IntegerField()
    point_log_name = models.ForeignKey(Shop, on_delete=models.CASCADE, max_length = 45, related_name='point_log_name', null=True)
    point_log_price = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name='point_log_price' ,null=True)

class Quiz(models.Model):
    quiz_id = models.IntegerField()
    quiz_content = models.CharField(max_length = 200, null=True)
    quiz_img = models.ImageField(upload_to='images/', null=True, blank=True)
    quiz_true = models.CharField(max_length = 100)
    quiz_false = models.CharField(max_length = 100)
    quiz_explanation = models.CharField(max_length = 300, null=True)
    #quiz_question = models.CharField(max_length = 200)

class Quiz_mypage(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='q_user', primary_key=True)
    quiz_pass = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_pass', null=True)
    quiz_nonepass = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='quiz_nonepass', null=True)

challengeapp/forms.py
from django import forms
from main.models import Category, Challenge, Activity, Stamp, N_badge, Challenge_Badge


class addChallengeForm(forms.ModelForm):
    class Meta:
        model = Challenge
        fields = ['challenge_name', 'introduction', 'categories', 'challenge_img']
        labels = {'challenge_name': '챌린지 이름', 'introduction': '챌린지 소개', 'categories': '카테고리', 'challenge_img': '챌린지 사진'}

class PostForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['challenge_id','activity_title', 'activity_date', 'activity_img', 'activity_content']
        labels = {'challenge_id': "챌린지 종류",'activity_title': '활용 내역', 'activity_date': '활동 날짜', 'activity_img': '활동 사진', 'activity_content': '활동 내용'}


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name'] 
        labels ={'name':"카테고리 이름"}

# 선재
class StampForm(forms.ModelForm):
    class Meta:
        model = Stamp
        fields = ['id', 'challenge_id', 'challenge_id']

# 선재
class N_BadgeForm(forms.ModelForm):
    class Meta:
        model = N_badge
        fields = ['id', 'challenge', 'n30_badge', 'n50_badge', 'n70_badge', 'n100_badge', 'badge_date']

# 선재
class Challenge_BadgeForm(forms.ModelForm):
    class Meta:
        model = Challenge_Badge
        fields = ['id', 'challenge_past']

challengeapp/views.py
from django.core.paginator import Paginator
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from main.models import Challenge, Activity, Challenge_mypage, Stamp, N_badge, Challenge_Badge, CustomUser, Category
import math
from challengeapp.forms import addChallengeForm, PostForm, CategoryForm, StampForm

# Create your views here.
def allchallengeandsearch(request):
    # 페이징 기능 (하단 숫자 리스트)
    all_boards = Challenge.objects.order_by("-challenge_start") # 모든 데이터 조회, 내림차순(-표시) 조회
    paginator = Paginator(all_boards, 5) # 한 페이지당 5개의 글 만 볼 수 있음 => 조절 가능
    page = int(request.GET.get('page', 1))
    board_list = paginator.get_page(page)
    return render(request, 'challengeapp/allchallengeandsearch.html', {'title':'Board List', 'board_list':board_list})

def addchallenge(request, challenge=None):
    if request.method == 'POST':
        form = addChallengeForm(request.POST, request.FILES, instance=challenge)
        if form.is_valid():
            challenge = form.save(commit=False)
            challenge.save() 
            return redirect('allchallengeandsearch')
    else:
        form = addChallengeForm
        return render(request, 'challengeapp/addchallenge.html', {'form':form})

def detailchallenge(request, challenge_name):
    challenge = get_object_or_404(Challenge, challenge_name = challenge_name)
    categories = Category.objects
    randomposts = Activity.objects.order_by("?")[:3]
    rankingposts = Activity.objects.order_by("activity_id")[:3]

    return render(request, 'challengeapp/detailchallenge.html', {'challenge' : challenge, 'categories':categories, 'randomposts':randomposts, 'rankingposts':rankingposts})

def challengeedit(request, challenge_name):
    challenge = get_object_or_404(Challenge, challenge_name=challenge_name)
    if request.method == 'POST':
        form = addChallengeForm(request.POST, instance=challenge)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('challengeapp/detailchallenge.html')
    else:
        form = addChallengeForm(instance=challenge)
        return render(request, 'challengeapp/challengeedit.html')

def categoryform(request, category=None):
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            category = form.save(commit=False)
            if Category.objects.filter(name=form.cleaned_data['name']):
                form = CategoryForm()
                error_message = "이미 존재하는 카테고리 입니다."
                #카테고리 만드는 팝업창 혹은 페이지로 이동하기
                return render(request, 'challengeapp/challengecategory.html', {'form':form, "error_message":error_message})
            else :
                category.name = form.cleaned_data['name']
                category.save()
            return redirect('allchallengeandsearch')
    else:
        form = CategoryForm(instance=category)
        #카테고리 만드는 팝업창 혹은 페이지로 이동하기
        return render(request, 'challengeapp/challengecategory.html', {'form':form})


def activity(request):
    posts = Activity.objects
    return render(request, 'challengeapp/activity.html', {'posts': posts })

def activitydetail(request, activity_title):
    post = Activity.objects.get(activity_title = activity_title)
    return render(request, 'challengeapp/activitydetail.html', {'post': post})


def mypage(request):
    # 로그인해야지만 들어갈 수 있음
    if not request.user.is_authenticated:
        return HttpResponse("로그인이 필요합니다.")
        
    Custom_user = CustomUser.objects.all()
    stamps = Stamp.objects.all()
    categories = Category.objects # 아직 규빈언니꺼랑 안합쳐서 Category form이 없음.
    posts = Activity.objects
    challenges = Challenge.objects

    return render(request, 'challengeapp/mypage.html', {'Custom_user':Custom_user, 'challegnes':challenges, 'posts': posts, 'categories':categories, 'stamps':stamps})


def newpost(request):
    return render(request, 'challengeapp/newpost.html')

def writepost(request, post=None):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance = post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('challengeapp/activity.html')
    else: 
        form = PostForm
        return render(request, 'challengeapp/newpost.html', {'post':post, 'form':form})

def postedit(request, activity_title):
    post = get_object_or_404(Activity, activity_title = activity_title)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('challengeapp/activitydetail.html')
    else:
        form = PostForm(instance=post)
        return render(request, 'challengeapp/postedit.html', {'post':post})


def postdelete(request, activity_title):
    post = get_object_or_404(Activity, activity_title = activity_title)
    post.delete()
    return redirect('activity')

    
def search(request):
    content = Challenge.objects.all() # 모든 object들을 content에 저장
    c = request.GET.get('b','') # GET request의 인자중에 c값이 있으면 가져오고, 없으면 빈 문자열 넣기
    if c:
        content = content.filter(challenge_name__icontains=c)

    return render(request, 'challengeapp/search.html', { 'search':content , 'b':c})

def more(request):
    if 'id' in request.GET:
        challenge = get_object_or_404(Challenge,pk=request.GET.get('id'))
        return render(request, 'challengeapp/more.html', {'post': challenge})
    return HttpResponseRedirect('challengeapp/allchallengeandsearch/')
    

# 선재
# 도장판1
#def mypage(request):
    if request.method == "POST":
        form = StampForm(request.POST, request.FILES)
        if form.is_valid():
            return redirect('main')
    else:
        form = StampForm()
        return render(request, 'challengeapp/mypage.html', {'form':form})

# 도장판2 =  지우꺼랑 합쳐야됨.
#def mypage(request):
    stamps = Stamp.objects.all()
    categories = Category.objects # 아직 규빈언니꺼랑 안합쳐서 Category form이 없음.
    posts = Activity.objects
    challenges = Challenge.objects
    #post = 0
    #if post == 1:
        #challenge_img
    #return render(request, 'challengeapp/mypage.html', {'stamps':stamps}, {'categories':categories}, {'posts': posts})

    #user = request.user # 현재 로그인한 유저
    #stamp.activity_id = 0
    #if stamp.activity_id ==+ 1:

    #stamp.activity_id
   # stamp.challenge_id
    return render(request, 'challengeapp/mypage.html', {'challegnes':challenges, 'posts': posts, 'categories':categories, 'stamps':stamps})
    



# 배지
def badge(request):
    #c_badges = Challenge_Badge.objects.all()
    #categories = Category.objects # 아직 규빈언니꺼랑 안합쳐서 Category form이 없음.
    #posts = Activity.objects
    #challenges = Challenge.objects


    #n_badge = N_badge()
    #c_badge = Challenge_Badge()
    #if request.method == 'POST' :
        #c_badge.challenge_past = 0
        #if c_badge.challenge_past == 30 :
            #n_badge.n30_badge 
        #if c_badge.challenge_past == 50 :
            #n_badge.n50_badge
        #if c_badge.challenge_past == 70 :
            #n_badge.n70_badge
        #if c_badge.challenge_past == 70 :
            #n_badge.n100_badge

        #n_badge.n30_badge
        #n_badge.n50_badge
        #n_badge.n70_badge
        #n_badge.n100_badge
        #n_badge.badge_date 
        #c_badge.challenge_past

    return render(request, 'challengeapp/badge.html')

challengeapp/templates/challengeapp/activity.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'main/css/main.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/actdetail.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/activity.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/mypage.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/common.css' %}" />
{% endblock css %}

{% block content %}
<section class="page-section container font-green text-center font" id="challenge">
  <div class>
    <article class>
      <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"></h2>
      </div>
    </article>

    <article class="act-content-article container">

      <div class="my-content">
        <div class="act-title">
          <div class="act-img-b">
            <!-- 챌린지 대표사진 보이기 -->
            {{ activity.activity_img }}
            <img class="act-img" src="{% static 'challengeapp/img/badge.png' %}" alt="?">
            <!-- 챌린지 설명 보이기-->
            <div class="act-exp">
              <h4>{{ user.nickname }} 님의 <br>환경보호 활동🌳</h4>
              <br>
              <a class="de-title-btn" href="{% url 'writepost' %}">활동 추가하기</a>
            </div>
          </div>
        </div>
        <hr class="act-hr">
      </div>

      <!-- 챌린지 목록 드롭버튼 -->

      <div class="dropdown" style="float: left; margin-bottom: 30px;">
        <button class="dropbtn"type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">챌린지 선택 ▼</button>
        <div class="dropdown-menu dropdown-content" aria-labelledby="dropdownMenuButton1">
          {% for challenge in challenges.all %}
          <a class="dropdown-item" href="#"> {{ challenge.challenge_name }} </a>
          {% endfor %}
        </div>
      </div>
    </article>
  

    <article class="de-content-article container">
      <div class="de-img-b">
        <div class="rt-container">
          <div class="col-rt-12">
            <div class='demo-container'>
              <div class='carousel_act'>
                <input checked='checked' class='carousel__activator' id='carousel-slide-activator-1' name='carousel'
                  type='radio'>
                <div class='carousel__screen act-b'>
                  <div class='carousel__track'>

                    <br><br>
                    <!-- 챌린지 활동 모두 보이기 -->
                    <form method="POST">
                      {% for posts in posts.all %} 
                      <div class='carousel__item carousel__item--mobile-in-1 carousel__item--tablet-in-2 carousel__item--desktop-in-3'>
                        <div class="de-chimg-b">
                          {% if posts.activity_img %}
                          <a href="{% url 'activitydetail' posts.activity_title %}">
                            <img src =" {{ posts.activity_img.url }}" width="354" height="298">
                          </a>
                          <div class="de-chcon-b">
                            <!-- a태그 눌러서 액티비티 디테일 페이지로 이동 -->
                            <a href="#!">
                             <p class="de-chcon-p1" style="font-size: 20px;"><a style="font-size: 30px;" href="{% url 'activitydetail' posts.activity_title %}"> {{ posts.challenge_id }}</a> 
                                <br> {{ posts.activity_title }} </p>
                            </a>
                          </div>
                        </div>
                        {% endif %}
                        {% endfor %}                        
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </article>
    <br><br>


    <!-- mypage, badge, activity가 사용하는 aside -->
    <article class="aside-article">
      <div class="my-aside">
        <div class="my">
          <!-- 설정한 프로필 사진 보이기 -->
          <img class="aside-profile my-a" src="{% static 'challengeapp/img/profile.png' %}" alt="{{user.nickname}}">
          <p><br>{{ user.nickname }}님<br>
          반갑습니다! 🤗</p>
          <!--<hr class="my-aside-hr">-->
        </div>
        
        <div class="my-aside-b">
          <p class="my-aside-btn"><a class="my-a" href="{% url 'editinfo' %}">Profile</a></p>
          <p class="my-aside-btn"><a class="my-a" href="{% url 'quiznote' %}">Quiznote</a></p>
          <p class="my-aside-btn"><a class="my-a" href="{% url 'badge' %}">Badge</a></p>
          <p class="my-aside-btn"><a class="my-a" href="{% url 'activity' %}">Activity</a></p>
        </div>
      </div>
    </article>


  </div>
</section>

{% endblock %}

challengeapp/templates/challengeapp/addchallenge.html
{% extends 'main/base.html' %} 
{% load static %} 

{% block css %} 
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/addch.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/common.css' %}"/>
{% endblock css %} 

{% block content %} 


<section class="page-section container font-green text-center font" id="challenge">
    <div class>
        <article class>
            <div class="container">
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"></h2>
            </div>
        </article>

        <article class>
            <div class="container">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}   
                {{ error_message }}      
                <table class="table-center">
                    <tr>
                    <th class="add-th">제목</th>
                    <td class="add-td"><input id="id" type="text" class="add-title add-input" placeholder="챌린지의 이름을 적어주세요" name="challenge_name"></td>

                    </tr>
                    <tr>
                    <th class="add-th">내용</th>
                    <td class="add-td"><textarea rows="20" cols="100" placeholder="챌린지의 내용을 적어주세요(참여 방법, 목적, 인증 방법 등)" name="introduction"></textarea></td>

                    </tr>
                    <tr>
                    <th class="add-th">대표사진</th>
                    <td  class="p-img add-td">
                    <input type="file" class="file add-input" name="challenge_img">    
                    <!-- 사진을 추가했다면 추가한 사진 보이기 & 이미지 크기는 최대 600x600  -->
                    {% if challenge.challenge_img %} 
                        <img class="img-max" src="{{ challenge.challenge_img.url }}" >
                    {% else %} 
                        <!-- <img src="{% static 'challengeapp/img/addchallenge-p.png' %}"> -->
                        <img class="img-max" src="{% static 'challengeapp/img/addchallenge-p.png' %}" >
                    {% endif %}
                     
                    </td>  
                    </tr>
                    <tr>
                    <th class="add-th">기간</th>
                    <td class="add-td">
                        <input name="term" type="checkbox" value="2주" class="check add-input">2주
                        <input name="term" type="checkbox" value="1개월" class="check add-input">1개월
                        <input name="term" type="checkbox" value="3개월" class="check add-input">3개월
                    </td>
                    </tr>

                    <!-- <tr>
                        <th><label for="id_categories">Categories:</label></th><td><select name="categories" id="id_categories" multiple>
                        {% for category in categories.all %}
                            <option value="">{{category.name}}</option>
                        {% endfor %} 
                      </select></td>
                    </tr> -->
                </table>
                <br>
                <!-- <table>
                    {% csrf_token %}
                    {{form.as_table}} 
                </table> -->

                <p><a href="{% url 'challengecategory' %}"> 카테고리 추가하기 </a></p>
                <button type="submit" class="add-btn">신청하기</button>
                <!-- <button type="submit" class="add-btn">미리보기</button>
                <button type="submit" class="add-btn">임시저장</button> -->
                <!-- <button type="submit" class="add-btn">취소</button> -->
            </form>
            </div>
        </article>        
    </div>
</section>


{% endblock %}

challengeapp/templates/challengeapp/challengeedit.html
{% extends 'main/base.html' %} 
{% load static %} 

{% block css %} 
<link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/addch.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'challengeapp/css/common.css' %}"/>
{% endblock css %} 

{% block content %} 


<section class="page-section container font-green text-center font" id="challenge">
    <div class>
        <article class>
            <div class="container">
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"></h2>
            </div>
        </article>

        <article class>
            <div class="container">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}   
                {{ error_message }}      
                <table class="table-center">
                    <tr>
                    <th class="add-th">제목</th>
                    <td class="add-td"><input id="id" type="text" class="add-title add-input" placeholder="챌린지의 이름을 적어주세요" name="challenge_name"></td>

                    </tr>
                    <tr>
                    <th class="add-th">내용</th>
                    <td class="add-td"><textarea rows="20" cols="100" placeholder="챌린지의 내용을 적어주세요(참여 방법, 목적, 인증 방법 등)" name="introduction"></textarea></td>

                    </tr>
                    <tr>
                    <th class="add-th">대표사진</th>
                    <td  class="p-img add-td">
                    <input type="file" class="file add-input" name="challenge_img">    
                    <!-- 사진을 추가했다면 추가한 사진 보이기 & 이미지 크기는 최대 600x600  -->
                    {% if challenge.challenge_img %} 
                        <img class="img-max" src="{{ challenge.challenge_img.url }}" >
                    {% else %} 
                        <!-- <img src="{% static 'challengeapp/img/addchallenge-p.png' %}"> -->
                        <img class="img-max" src="{% static 'challengeapp/img/addchallenge-p.png' %}" >
                    {% endif %}
                     
                    </td>  
                    </tr>
                    <tr>
                    <th class="add-th">기간</th>
                    <td class="add-td">
                        <input type="checkbox" value="2주" class="check add-input">2주
                        <input type="checkbox" value="1개월" class="check add-input">1개월
                        <input type="checkbox" value="3개월" class="check add-input">3개월
                    </td>
                    </tr>

                    <!-- <tr>
                        <th><label for="id_categories">Categories:</label></th><td><select name="categories" id="id_categories" multiple>
                        {% for category in categories.all %}
                            <option value="">{{category.name}}</option>
                        {% endfor %} 
                      </select></td>
                    </tr> -->
                </table>
                <br>
                <!-- <table>
                    {% csrf_token %}
                    {{form.as_table}} 
                </table> -->

                <!-- <p><a href="{% url 'challengecategory' %}"> 카테고리 추가하기 </a></p> -->
                <button type="submit" class="add-btn">신청하기</button>
                <!-- <button type="submit" class="add-btn">미리보기</button>
                <button type="submit" class="add-btn">임시저장</button> -->
                <!-- <button type="submit" class="add-btn">취소</button> -->
            </form>
            </div>
        </article>        
    </div>
</section>


{% endblock %}